Name: Product
Host: 0.0.0.0
Port: 8001

ProductRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: product.rpc

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

Kafka:
  Addrs:
    - kafka:9092
  Topic: cache-sync-topic